### ISSUE TITLE
Title What Sets Us Apart ?

### ISSUE THREAD

**Issue by Zineb2a** [6amigos-concordia/6amigos-soen341projectF2023#24]
I've added the section Featured Brokers, you can go ahead and fix the title of What Sets Us Apart ?

**Comment by asu21244** [comment]
I can't fetch your changements, because it says that "there's unresolved conflicts in the working directory". Do you know why?

**Comment by Zineb2a** [comment]
Do you have something to commit or you just have to pull ?

**Comment by asu21244** [comment]
Fixed the responsiveness of "What sets us apart". Is it good?
