### ISSUE TITLE
mortgage calculator 

### ISSUE THREAD

**Issue by HaifaaJanoudi** [6amigos-concordia/6amigos-soen341projectF2023#26]
the Mortgage calculator has been sent to the frontend branch and it needs a little work. 
the code was functioning properly before importing it to the frontend branch, but its no longer working. 
there must be a small issue with the index.js file or the app.jsx file.

**Comment by asu21244** [comment]
Its now working but a lot of issues are now arising. First of all, the mortgage calculator is not responsive. Second of all, the sizing and everything is pretty off(change CSS).
