### ISSUE TITLE
automatic unit testing

### ISSUE THREAD

**Issue by HaifaaJanoudi** [6amigos-concordia/6amigos-soen341projectF2023#40]
automatic unit testing is not working with frontend. All required dependencies were installed and despite that, errors were still showing up. the other frontend team members could try and run it, maybe its an issue with my computer. 
Here are the useful videos that I used:
 https://youtu.be/Xe9OA18PF_o?si=NrKCtoZuECZ3vWnH 
 https://youtu.be/WW6ZUw9IExA?si=8HvZBAqSZXmqUSZz

**Comment by huy2272** [comment]
This is related to issue #22
